
import { Language, RegionData, TranslationKey } from './types';

export const TRANSLATIONS: Record<Language, Record<TranslationKey, string>> = {
  [Language.EN]: {
    appTitle: 'Gharas',
    heroTitle: 'Smart Farming for a Greener Future',
    heroDesc: 'Empowering farmers with AI diagnosis, smart crop recommendations based on your location, and real-time IoT monitoring.',
    serviceDiagnosis: 'AI Plant Diagnosis',
    serviceDiagnosisDesc: 'Identify plant diseases instantly with our advanced AI model.',
    serviceCrops: 'Smart Crop Guide',
    serviceCropsDesc: 'Find the perfect crops for your specific region in Saudi Arabia.',
    serviceIoT: 'Smart Irrigation (IoT)',
    serviceIoTDesc: 'Monitor soil health and automate irrigation with real-time data.',
    startBtn: 'Get Started',
    uploadImage: 'Upload Plant Leaf',
    analyzeBtn: 'Analyze Health',
    analyzing: 'Analyzing...',
    healthy: 'Healthy',
    infected: 'Infected',
    confidence: 'Confidence',
    treatments: 'Treatment Recommendations',
    tips: 'Care Tips',
    selectRegion: 'Select Your Region',
    detectLocation: 'Use My Current Location',
    detecting: 'Detecting location...',
    regionCentral: 'Central Region',
    regionEast: 'Eastern Region',
    regionWest: 'Western Region',
    regionSouth: 'Southern Region',
    regionNorth: 'Northern Region',
    irrigationDashboard: 'Irrigation Monitor',
    soilMoisture: 'Soil Moisture',
    lastWatered: 'Last Watered',
    irrigationStatus: 'System Status',
    npkDashboard: 'Nutrient (NPK) Sensors',
    statusGood: 'Optimal',
    statusLow: 'Low',
    statusHigh: 'High',
    nitrogen: 'Nitrogen (N)',
    phosphorus: 'Phosphorus (P)',
    potassium: 'Potassium (K)',
    temp: 'Temperature',
    acidity: 'pH Level',
    // New Sections
    featuresTitle: 'What Distinguishes Gharas',
    feature1Title: 'AI Precision',
    feature1Desc: 'Advanced algorithms for high-accuracy disease diagnosis.',
    feature2Title: 'Localized Solutions',
    feature2Desc: 'Data tailored to the Saudi climate and soil types.',
    feature3Title: 'IoT Integration',
    feature3Desc: 'Real-time monitoring via seamless sensor connectivity.',
    feature4Title: 'Sustainability',
    feature4Desc: 'Promoting water conservation and soil health.',
    howToTitle: 'How to Use the Platform',
    howToSubtitle: 'Start your smart farming journey in 3 simple steps',
    step1Title: 'Select Service',
    step1Desc: 'Choose from Diagnosis, Crops, or IoT services.',
    step2Title: 'Input Data',
    step2Desc: 'Upload a photo, set location, or connect sensors.',
    step3Title: 'Get Results',
    step3Desc: 'Receive instant insights and actionable advice.',
    ctaTitle: 'Ready to start your smart farming experience?',
    ctaBtn: 'Explore Services',
    aboutUsTitle: 'About Gharas',
    aboutUsDesc: 'Gharas is a leading smart agriculture platform dedicated to empowering farmers through technology for a sustainable and greener future.',
    quickLinksTitle: 'Quick Links',
    contactUsTitle: 'Contact Us',
  },
  [Language.AR]: {
    appTitle: 'غراس',
    heroTitle: 'زراعة ذكية لمستقبل أخضر',
    heroDesc: 'نمكّن المزارعين بأدوات تشخيص الذكاء الاصطناعي، وتوصيات المحاصيل الدقيقة، وأنظمة المراقبة الذكية.',
    serviceDiagnosis: 'تشخيص أمراض النبات',
    serviceDiagnosisDesc: 'اكتشف أمراض نباتاتك فوراً باستخدام تقنيات الذكاء الاصطناعي المتطورة.',
    serviceCrops: 'دليل المحاصيل الذكي',
    serviceCropsDesc: 'تعرف على أفضل المحاصيل المناسبة للزراعة في منطقتك.',
    serviceIoT: 'الري الذكي (IoT)',
    serviceIoTDesc: 'راقب صحة التربة وتحكم في الري آلياً بناءً على بيانات حقيقية.',
    startBtn: 'ابدأ الآن',
    uploadImage: 'ارفع صورة الورقة',
    analyzeBtn: 'تحليل الحالة',
    analyzing: 'جاري التحليل...',
    healthy: 'سليمة',
    infected: 'مريضة',
    confidence: 'نسبة التأكد',
    treatments: 'توصيات العلاج',
    tips: 'نصائح للعناية',
    selectRegion: 'اختر المنطقة',
    detectLocation: 'استخدم موقعي الحالي',
    detecting: 'جاري تحديد الموقع...',
    regionCentral: 'المنطقة الوسطى',
    regionEast: 'المنطقة الشرقية',
    regionWest: 'المنطقة الغربية',
    regionSouth: 'المنطقة الجنوبية',
    regionNorth: 'المنطقة الشمالية',
    irrigationDashboard: 'مراقبة الري',
    soilMoisture: 'رطوبة التربة',
    lastWatered: 'آخر عملية ري',
    irrigationStatus: 'حالة النظام',
    npkDashboard: 'حساسات العناصر (NPK)',
    statusGood: 'ممتاز',
    statusLow: 'منخفض',
    statusHigh: 'مرتفع',
    nitrogen: 'نيتروجين (N)',
    phosphorus: 'فوسفور (P)',
    potassium: 'بوتاسيوم (K)',
    temp: 'درجة الحرارة',
    acidity: 'الحموضة (pH)',
    // New Sections
    featuresTitle: 'ما يميز غراس',
    feature1Title: 'دقة الذكاء الاصطناعي',
    feature1Desc: 'خوارزميات متطورة لتشخيص الأمراض بدقة عالية.',
    feature2Title: 'حلول مخصصة للمملكة',
    feature2Desc: 'بيانات زراعية دقيقة تتناسب مع مناخ وتربة مناطق السعودية.',
    feature3Title: 'تكامل تقني (IoT)',
    feature3Desc: 'ربط مباشر مع أجهزة الاستشعار لمراقبة حية ومستمرة.',
    feature4Title: 'استدامة بيئية',
    feature4Desc: 'تقنيات تساعد في توفير المياه وتحسين جودة المحاصيل.',
    howToTitle: 'كيفية استخدام الموقع',
    howToSubtitle: 'ابدأ رحلتك الزراعية في 3 خطوات بسيطة',
    step1Title: 'اختر الخدمة',
    step1Desc: 'حدد الخدمة التي تحتاجها (تشخيص، محاصيل، ري).',
    step2Title: 'أدخل البيانات',
    step2Desc: 'ارفع صورة النبات، حدد موقعك، أو اربط الحساسات.',
    step3Title: 'احصل على النتائج',
    step3Desc: 'تلقى توصيات فورية وحلول عملية لتحسين زراعتك.',
    ctaTitle: 'هل أنت مستعد لبدء تجربتك الزراعية الذكية؟',
    ctaBtn: 'تصفح الخدمات',
    aboutUsTitle: 'نبذة عن غراس',
    aboutUsDesc: 'غراس هي منصة سعودية رائدة تهدف إلى إحداث نقلة نوعية في القطاع الزراعي من خلال دمج التقنية الحديثة والذكاء الاصطناعي لخدمة المزارعين والهواة.',
    quickLinksTitle: 'روابط سريعة',
    contactUsTitle: 'تواصل معنا',
  }
};

export const SAUDI_REGIONS: RegionData[] = [
  {
    id: 'central',
    nameEn: 'Central Region',
    nameAr: 'المنطقة الوسطى',
    crops: [
      { nameEn: 'Date Palms', nameAr: 'النخيل', image: 'https://picsum.photos/id/106/200/200', season: 'Year-round' },
      { nameEn: 'Wheat', nameAr: 'القمح', image: 'https://picsum.photos/id/109/200/200', season: 'Winter' },
    ]
  },
  {
    id: 'west',
    nameEn: 'Western Region',
    nameAr: 'المنطقة الغربية',
    crops: [
      { nameEn: 'Figs', nameAr: 'التين', image: 'https://picsum.photos/id/292/200/200', season: 'Summer' },
      { nameEn: 'Grapes', nameAr: 'العنب', image: 'https://picsum.photos/id/430/200/200', season: 'Summer' },
    ]
  },
  {
    id: 'east',
    nameEn: 'Eastern Region',
    nameAr: 'المنطقة الشرقية',
    crops: [
      { nameEn: 'Tomatoes', nameAr: 'الطماطم', image: 'https://picsum.photos/id/495/200/200', season: 'Winter/Spring' },
      { nameEn: 'Watermelon', nameAr: 'البطيخ', image: 'https://picsum.photos/id/225/200/200', season: 'Summer' },
    ]
  },
  {
    id: 'south',
    nameEn: 'Southern Region',
    nameAr: 'المنطقة الجنوبية',
    crops: [
      { nameEn: 'Coffee', nameAr: 'البن الخولاني', image: 'https://picsum.photos/id/514/200/200', season: 'Year-round' },
      { nameEn: 'Mango', nameAr: 'المانجو', image: 'https://picsum.photos/id/365/200/200', season: 'Summer' },
      { nameEn: 'Bananas', nameAr: 'الموز', image: 'https://picsum.photos/id/114/200/200', season: 'Year-round' },
    ]
  },
  {
    id: 'north',
    nameEn: 'Northern Region',
    nameAr: 'المنطقة الشمالية',
    crops: [
      { nameEn: 'Olives', nameAr: 'الزيتون', image: 'https://picsum.photos/id/250/200/200', season: 'Autumn' },
      { nameEn: 'Citrus', nameAr: 'الحمضيات', image: 'https://picsum.photos/id/355/200/200', season: 'Winter' },
    ]
  }
];

export const MOCK_SENSOR_DATA = Array.from({ length: 12 }, (_, i) => ({
  time: `${i + 1}:00`,
  moisture: 40 + Math.random() * 30,
}));